# Generated by Django 5.0 on 2024-01-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
