# Generated by Django 5.0 on 2024-01-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_rename_dashboard_main_wallet_accountbalance_dashboard_mainwallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_all_transactions',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_deposit_bonus',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_investment_bonus',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_rank_achieved',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_referral_bonus',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_deposit',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_investment',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_profit',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_referral',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_ticket',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_transfer',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dash_total_withdraw',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dashboard_mainwallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='dashboard_profitwallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='deposit_logs_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='deposit_logs_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='deposit_mainwallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='deposit_profitwallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='ranking_badge_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='ranking_badge_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='referral_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='referral_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='schema_logs_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='schema_logs_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='schemas_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='schemas_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='transactions_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='transactions_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='withdraw_logs_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='withdraw_logs_profit_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='withdraw_main_wallet',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='withdraw_profit_wallet',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='acc_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='deposit_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='gift',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_amount9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_date9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_plan9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='referral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='total_active',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_amount9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_date9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_others',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_paymentmode9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_status9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
