# Generated by Django 5.0 on 2024-01-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_remove_accountbalance_acc_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='dashboard_mainwallet',
            new_name='dashboard_main_wallet',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='dashboard_profitwallet',
            new_name='dashboard_profit_wallet',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='deposit_mainwallet',
            new_name='deposit_main_wallet',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='deposit_profitwallet',
            new_name='deposit_profit_wallet',
        ),
    ]
