# Generated by Django 5.0 on 2024-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_alter_accountbalance_dash_all_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='dash_rank_achieved',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
        ),
    ]
