# Generated by Django 5.0 on 2024-01-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_accountbalance_add_money_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ImageField(upload_to='profile_pics')),
                ('imagePassport', models.ImageField(upload_to='profile_pics')),
            ],
        ),
    ]
